title: Plamen Pasliev # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Looking for new opportunities starting April 2020. 
  <a href="https://masterschool.eitdigital.eu/programmes/dsc/">EIT Digital Data Science</a> MSc graduate.
  Particularly interested in unveiling bias in AI and explaining why complex algorithms make certain decisions.
  <br><br>
  Currently a part-time Data Scientist at <a href="https://www.wayfair.com/">Wayfair</a>. Helped build end-to-end projects such as personalizing their <a href="https://www.wayfair.com/help/index">Help & Contact</a> page.
  Developed a strong command of data science tools such as: Python, SQL, Pandas, Numpy, Matplotlib, SK-learn, PyTorch, 
  Keras and TensorFlow. 
  <br><br>
  <a href="https://www.linkedin.com/in/plamenpasliev/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
